language: node_js

node_js:
  - node

install:
  - npm ci

script:
  - npm run test

after_success:
  - echo -e "Test Success"

after_script:
  - sed -i 's|SF:../../home/travis/build/koonfoon/generator-vscode-typescript-jest/|SF:|g' coverage/lcov.info && cat ./coverage/lcov.info | coveralls -v

