notifications:
  email: false
language: node_js
services:
- docker
node_js:
- '14'
git:
  depth: false
before_install: 
install:
- npm ci
script:
- npm run test
after_success:
- echo -e "Test Success"
after_script:
- sed -i 's|SF:../../home/travis/build/koonfoon/generator-vscode-typescript-jest/|SF:|g'
  coverage/lcov.info && cat ./coverage/lcov.info | coveralls -v
before_deploy:
- echo $TRAVIS_BRANCH
- export Git_Branch=$(echo $TRAVIS_BRANCH)
- echo $Git_Branch
- git switch $Git_Branch
- git branch
- git branch --show-current
- echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
- docker pull gittools/gitversion:5.3.5-linux-alpine.3.10-x64-netcoreapp3.1
- export GitVersion_FullSemVer=$(docker run --rm -v "$(pwd):/repo" gittools/gitversion:5.3.5-linux-alpine.3.10-x64-netcoreapp3.1
  /repo -output json -showvariable FullSemVer)
- echo $GitVersion_FullSemVer
- npm run release -- $GitVersion_FullSemVer --no-tests --no-publish --no-yarn --message
  "'%s' +semver:skip [ci skip]"
deploy:
  provider: npm
  skip_cleanup: true
  email: koonfoon@gmail.com
  api_key:
    secure: SH53SlPSTS4akmAICTuKZrnFYT+v7f7BzkxOXqzX92GzV+Ojq4jmSLyYpqifPvrwW98PykuNM4J9QR4AUYSR2+zrn9jbDJQ0G5QZLTABgeQU2UYur3ML7+mjBMZ1EQXvxmkSUPD6iK97jaPca2LQgmpy9IL/cB0Is8671TLKHBmOJBjmk35raaONjjlfYutafQFPItI6nVXtVFDZUW9/7iQiwuvidD7QU41JncNcOsADp9HHGRA0WNqhMIVJ7n6QevH6hPrg2L+sTCZuTRl+ABt/KLwljAHgTcDQRMZ/Guw+mmtf6LhxuzIs3RlVwVVneu40YWLNtr4rRG5KGMtSnJbMahzLMObHBa9BQm+Q+u4sgTSJzWwVNKAThlVBIYS1BZJH3HYYsCmQ33PeY128B2oqhx2Wo+K7PILw2p/vvXpBxnA3dOjN2ZJ0gAY+bF6MGRedDCJB2n2x9vNSLYcpQKvm8xqAoanDzzfrvxs+OVFQnMGO+3iYkHtmFnJ+2BaZHpt2DSPzMHN7LmdMej3D9x7z26y7o/NM2f6JKtWjDZGxpc2wnWebOpDWoYyYibXyWkHiozBt5blmEIJOsjJWb8T8nIpUSM6aE7yXVlRd08f/Uyvvs+dUB7N7JjGwdOgyMZV0vWdJa3x3uqri7i/rq6RZSDeH7TCUSBxo1tvwNec=
  on:
    branch: master
