language: node_js

node_js:
  - node

install:
  - npm ci --no-optional

script:
  - npm run test:coverallsVerbose

after_success:
  - echo -e "Test Success"

## after_script: cat ./coverage/lcov.info | coveralls

