name: Node.js CI Test

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build:

    permissions:
        checks: write
        pull-requests: write
        contents: write
    
    # Don't know run if trigger by dependabot, but run if tirgger manually
    if: ${{ github.triggering_actor != 'dependabot[bot]' }}  

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci   # install all dependencies
    - run: npm run build --if-present    
    - run: npm run test   # run test for ci only

    - name: Report test converage
      uses: ArtiomTr/jest-coverage-report-action@v2
      with:
        skip-step: all
        coverage-file: ./coverage/coverage-final.json

        